services:
  backend:
    build:
      context: .
      target: backend
    container_name: schedulezap-backend
    command: ["node", "index.js"]
    restart: unless-stopped
    ports:
      - "8999:8999" # Backend API port
    volumes:
      - ./backend/schedules.json:/app/schedules.json # Persist schedules.json
    environment:
      - NODE_ENV=production
      - VITE_PASSWORD=${VITE_PASSWORD:-S3nha!2024@zap}
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8999/api/schedules', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      target: frontend
    container_name: schedulezap-frontend
    command: ["serve", "-s", "dist", "-l", "8988"]
    restart: unless-stopped
    ports:
      - "8988:8988" # Frontend port
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_PASSWORD=${VITE_PASSWORD:-S3nha!2024@zap}
