version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8988"
    volumes:
      - schedules:/app/backend/schedules.json
    environment:
      - NODE_ENV=production
      - APP_URL=${APP_URL:-http://localhost}
      - API_URL=${API_URL:-http://localhost}
    restart: unless-stopped
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  schedules:
    driver: local
