services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:8988"
    command: node server.js
    environment:
      - NODE_ENV=production
    restart: always
