services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "80:8988"
    volumes:
      - ./backend/schedules.json:/app/backend/schedules.json
    environment:
      - NODE_ENV=production
      - PORT=8988
      - BACKEND_PORT=8999
    restart: always
    stop_grace_period: 30s
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8988 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
